import { User, Project, Milestone, Task, TaskStatus, TaskPriority, Notification } from './types';

export const mockUsers: User[] = [
  { id: '1', name: 'Sarah Chen', email: 'sarah@urbanweb.host', role: 'admin', department: 'Management' },
  { id: '2', name: 'Marcus Johnson', email: 'marcus@urbanweb.host', role: 'manager', department: 'Design' },
  { id: '3', name: 'Emily Rodriguez', email: 'emily@urbanweb.host', role: 'employee', department: 'Design' },
  { id: '4', name: 'David Kim', email: 'david@urbanweb.host', role: 'employee', department: 'Video' },
  { id: '5', name: 'Lisa Zhang', email: 'lisa@urbanweb.host', role: 'employee', department: 'Development' },
  { id: '6', name: 'Client Portal', email: 'client@example.com', role: 'viewer', department: 'External' },
];

export const mockProjects: Project[] = [
  {
    id: 'proj-1',
    title: 'TechCorp Rebrand',
    description: 'Complete brand identity redesign for TechCorp including logo, website, and marketing materials',
    client: 'TechCorp Inc.',
    status: 'active',
    startDate: new Date('2024-01-15'),
    endDate: new Date('2024-03-30'),
    teamMembers: ['2', '3', '5'],
    color: '#3B82F6',
  },
  {
    id: 'proj-2',
    title: 'E-commerce Platform Launch',
    description: 'Design and develop a modern e-commerce platform with custom CMS',
    client: 'RetailHub',
    status: 'active',
    startDate: new Date('2024-02-01'),
    endDate: new Date('2024-04-15'),
    teamMembers: ['3', '5'],
    color: '#10B981',
  },
  {
    id: 'proj-3',
    title: 'Product Launch Video',
    description: 'Create promotional video series for new product line',
    client: 'InnovateTech',
    status: 'active',
    startDate: new Date('2024-02-10'),
    endDate: new Date('2024-03-10'),
    teamMembers: ['4'],
    color: '#F59E0B',
  },
];

export const mockMilestones: Milestone[] = [
  {
    id: 'mile-1',
    title: 'Brand Discovery & Research',
    description: 'Complete initial research and concept development',
    projectId: 'proj-1',
    dueDate: new Date('2024-02-15'),
    status: 'completed',
    progress: 100,
  },
  {
    id: 'mile-2',
    title: 'Logo & Visual Identity',
    description: 'Design and finalize logo and brand guidelines',
    projectId: 'proj-1',
    dueDate: new Date('2024-03-01'),
    status: 'active',
    progress: 65,
  },
  {
    id: 'mile-3',
    title: 'Website Design',
    description: 'Complete website mockups and prototypes',
    projectId: 'proj-1',
    dueDate: new Date('2024-03-20'),
    status: 'active',
    progress: 30,
  },
  {
    id: 'mile-4',
    title: 'Platform Architecture',
    description: 'Design database schema and API structure',
    projectId: 'proj-2',
    dueDate: new Date('2024-02-20'),
    status: 'active',
    progress: 80,
  },
  {
    id: 'mile-5',
    title: 'Video Production',
    description: 'Film and edit primary promotional video',
    projectId: 'proj-3',
    dueDate: new Date('2024-02-28'),
    status: 'active',
    progress: 45,
  },
];

export const mockTasks: Task[] = [
  {
    id: 'task-1',
    title: 'Create brand color palette variations',
    description: 'Develop 3 color palette options based on client feedback',
    status: 'in-progress',
    priority: 'high',
    type: 'design',
    assignedTo: ['3'],
    createdBy: '2',
    createdAt: new Date('2024-02-12'),
    updatedAt: new Date('2024-02-14'),
    dueDate: new Date('2024-02-20'),
    milestoneId: 'mile-2',
    subtasks: [
      { id: 'sub-1', title: 'Research competitor colors', completed: true },
      { id: 'sub-2', title: 'Create palette 1', completed: true },
      { id: 'sub-3', title: 'Create palette 2', completed: false },
      { id: 'sub-4', title: 'Create palette 3', completed: false },
    ],
    tags: ['branding', 'design'],
    estimatedHours: 8,
    actualHours: 5,
    internalNotes: 'Client prefers blues and greens',
  },
  {
    id: 'task-2',
    title: 'Design homepage hero section',
    description: 'Create multiple hero section concepts for the homepage',
    status: 'todo',
    priority: 'medium',
    type: 'design',
    assignedTo: ['3'],
    createdBy: '2',
    createdAt: new Date('2024-02-13'),
    updatedAt: new Date('2024-02-13'),
    dueDate: new Date('2024-02-22'),
    milestoneId: 'mile-3',
    subtasks: [
      { id: 'sub-5', title: 'Sketch initial concepts', completed: false },
      { id: 'sub-6', title: 'Create high-fidelity mockups', completed: false },
    ],
    tags: ['web-design', 'ui'],
    estimatedHours: 12,
  },
  {
    id: 'task-3',
    title: 'Edit product demo footage',
    description: 'Edit raw footage into 90-second product demo',
    status: 'in-progress',
    priority: 'urgent',
    type: 'video-editing',
    assignedTo: ['4'],
    createdBy: '2',
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-14'),
    dueDate: new Date('2024-02-18'),
    milestoneId: 'mile-5',
    subtasks: [
      { id: 'sub-7', title: 'Review raw footage', completed: true },
      { id: 'sub-8', title: 'Create rough cut', completed: true },
      { id: 'sub-9', title: 'Add transitions and effects', completed: false },
      { id: 'sub-10', title: 'Color grading', completed: false },
      { id: 'sub-11', title: 'Sound design', completed: false },
    ],
    tags: ['video', 'editing'],
    estimatedHours: 16,
    actualHours: 10,
    internalNotes: 'Client wants upbeat music',
  },
  {
    id: 'task-4',
    title: 'Implement shopping cart functionality',
    description: 'Build shopping cart with local storage and checkout flow',
    status: 'in-progress',
    priority: 'high',
    type: 'development',
    assignedTo: ['5'],
    createdBy: '2',
    createdAt: new Date('2024-02-11'),
    updatedAt: new Date('2024-02-14'),
    dueDate: new Date('2024-02-25'),
    milestoneId: 'mile-4',
    subtasks: [
      { id: 'sub-12', title: 'Design cart state management', completed: true },
      { id: 'sub-13', title: 'Implement add to cart', completed: true },
      { id: 'sub-14', title: 'Build cart UI', completed: false },
      { id: 'sub-15', title: 'Integrate payment gateway', completed: false },
    ],
    tags: ['development', 'frontend'],
    estimatedHours: 20,
    actualHours: 12,
  },
  {
    id: 'task-5',
    title: 'Logo revision - Round 2',
    description: 'Implement client feedback from first review',
    status: 'review',
    priority: 'high',
    type: 'revision',
    assignedTo: ['3'],
    createdBy: '2',
    createdAt: new Date('2024-02-08'),
    updatedAt: new Date('2024-02-13'),
    dueDate: new Date('2024-02-16'),
    milestoneId: 'mile-2',
    subtasks: [
      { id: 'sub-16', title: 'Adjust typography', completed: true },
      { id: 'sub-17', title: 'Refine icon design', completed: true },
      { id: 'sub-18', title: 'Prepare presentation', completed: true },
    ],
    tags: ['branding', 'revision'],
    estimatedHours: 6,
    actualHours: 6,
    internalNotes: 'Waiting for final client approval',
  },
  {
    id: 'task-6',
    title: 'Deploy staging environment',
    description: 'Set up and deploy staging server for client testing',
    status: 'todo',
    priority: 'medium',
    type: 'deployment',
    assignedTo: ['5'],
    createdBy: '2',
    createdAt: new Date('2024-02-14'),
    updatedAt: new Date('2024-02-14'),
    dueDate: new Date('2024-02-28'),
    milestoneId: 'mile-4',
    subtasks: [
      { id: 'sub-19', title: 'Configure server', completed: false },
      { id: 'sub-20', title: 'Set up CI/CD pipeline', completed: false },
      { id: 'sub-21', title: 'Test deployment', completed: false },
    ],
    tags: ['deployment', 'devops'],
    estimatedHours: 8,
  },
  {
    id: 'task-7',
    title: 'Create brand guidelines document',
    description: 'Compile comprehensive brand guidelines PDF',
    status: 'completed',
    priority: 'medium',
    type: 'branding',
    assignedTo: ['3'],
    createdBy: '2',
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-02-12'),
    dueDate: new Date('2024-02-12'),
    milestoneId: 'mile-2',
    subtasks: [
      { id: 'sub-22', title: 'Write guidelines content', completed: true },
      { id: 'sub-23', title: 'Design document layout', completed: true },
      { id: 'sub-24', title: 'Export final PDF', completed: true },
    ],
    tags: ['branding', 'documentation'],
    estimatedHours: 10,
    actualHours: 11,
  },
  {
    id: 'task-8',
    title: 'Weekly content review meeting',
    description: 'Review all ongoing creative work with team',
    status: 'todo',
    priority: 'low',
    type: 'other',
    assignedTo: ['2', '3', '4', '5'],
    createdBy: '1',
    createdAt: new Date('2024-02-14'),
    updatedAt: new Date('2024-02-14'),
    dueDate: new Date('2024-02-16'),
    milestoneId: 'mile-2',
    subtasks: [],
    tags: ['meeting', 'review'],
    estimatedHours: 2,
    recurring: {
      frequency: 'weekly',
      interval: 1,
    },
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    userId: '3',
    type: 'deadline-approaching',
    message: 'Task "Create brand color palette variations" is due in 3 days',
    taskId: 'task-1',
    read: false,
    createdAt: new Date('2024-02-14T09:00:00'),
  },
  {
    id: 'notif-2',
    userId: '4',
    type: 'deadline-approaching',
    message: 'Task "Edit product demo footage" is due tomorrow',
    taskId: 'task-3',
    read: false,
    createdAt: new Date('2024-02-14T08:30:00'),
  },
  {
    id: 'notif-3',
    userId: '3',
    type: 'revision-requested',
    message: 'Logo revision is ready for final review',
    taskId: 'task-5',
    read: true,
    createdAt: new Date('2024-02-13T14:20:00'),
  },
  {
    id: 'notif-4',
    userId: '5',
    type: 'task-assigned',
    message: 'You have been assigned "Deploy staging environment"',
    taskId: 'task-6',
    read: false,
    createdAt: new Date('2024-02-14T10:15:00'),
  },
];

export const getCurrentUser = (): User => {
  return mockUsers[2];
};

export const getUserById = (id: string): User | undefined => {
  return mockUsers.find(u => u.id === id);
};
